export const API_CONFIG = {
  FILMS_SERVICE: process.env.NEXT_PUBLIC_FILMS_API_URL || 'http://192.168.0.185:8000',
  AUTH_SERVICE: process.env.NEXT_PUBLIC_AUTH_API_URL || 'http://192.168.0.78:3000',
  RESERVATIONS_SERVICE: process.env.NEXT_PUBLIC_RESERVATIONS_SERVICE_URL || '',
};